//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChallengeApp.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ChallengeApp.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accepting challenge.
        /// </summary>
        public static string AcceptingChallenge {
            get {
                return ResourceManager.GetString("AcceptingChallenge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Met the challenge.
        /// </summary>
        public static string AccomplishedTheChallenge {
            get {
                return ResourceManager.GetString("AccomplishedTheChallenge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add some friends.
        /// </summary>
        public static string AddSomeFriends {
            get {
                return ResourceManager.GetString("AddSomeFriends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a minute ago.
        /// </summary>
        public static string AMinuteAgo {
            get {
                return ResourceManager.GetString("AMinuteAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to an hour ago.
        /// </summary>
        public static string AnHourAgo {
            get {
                return ResourceManager.GetString("AnHourAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Challenge.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archive.
        /// </summary>
        public static string Archive {
            get {
                return ResourceManager.GetString("Archive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Challenge a friend.
        /// </summary>
        public static string ChallengeAFriend {
            get {
                return ResourceManager.GetString("ChallengeAFriend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Challenged you.
        /// </summary>
        public static string ChallengedYou {
            get {
                return ResourceManager.GetString("ChallengedYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Challenge.
        /// </summary>
        public static string ChallengeVerb {
            get {
                return ResourceManager.GetString("ChallengeVerb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments.
        /// </summary>
        public static string Comments {
            get {
                return ResourceManager.GetString("Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Account.
        /// </summary>
        public static string CreateAccount {
            get {
                return ResourceManager.GetString("CreateAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating account.
        /// </summary>
        public static string CreatingAccount {
            get {
                return ResourceManager.GetString("CreatingAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discover.
        /// </summary>
        public static string Discover {
            get {
                return ResourceManager.GetString("Discover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your feed is empty, what about add some friends?.
        /// </summary>
        public static string EmptyFeedMessage {
            get {
                return ResourceManager.GetString("EmptyFeedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No notifications by now, what about challenge a friend?.
        /// </summary>
        public static string EmptyNotificationsMessage {
            get {
                return ResourceManager.GetString("EmptyNotificationsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are already following this user.
        /// </summary>
        public static string ERROR_ALREADY_FOLLOWING {
            get {
                return ResourceManager.GetString("ERROR_ALREADY_FOLLOWING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You were not following this user.
        /// </summary>
        public static string ERROR_ALREADY_NOT_FOLLOWING {
            get {
                return ResourceManager.GetString("ERROR_ALREADY_NOT_FOLLOWING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill at least one field.
        /// </summary>
        public static string ERROR_AT_LEAST_ONE_FIELD {
            get {
                return ResourceManager.GetString("ERROR_AT_LEAST_ONE_FIELD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You already doubted this challenge.
        /// </summary>
        public static string ERROR_CHALLENGE_ALREADY_DOUBTED {
            get {
                return ResourceManager.GetString("ERROR_CHALLENGE_ALREADY_DOUBTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You already liked this challenge.
        /// </summary>
        public static string ERROR_CHALLENGE_ALREADY_KILLED {
            get {
                return ResourceManager.GetString("ERROR_CHALLENGE_ALREADY_KILLED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Challenge has been already refused.
        /// </summary>
        public static string ERROR_CHALLENGE_ALREADY_REFUSED {
            get {
                return ResourceManager.GetString("ERROR_CHALLENGE_ALREADY_REFUSED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This challenge is finalized (accepted or refused).
        /// </summary>
        public static string ERROR_CHALLENGE_IS_FINALIZED {
            get {
                return ResourceManager.GetString("ERROR_CHALLENGE_IS_FINALIZED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This user only accepts followers challenges.
        /// </summary>
        public static string ERROR_CHALLENGE_NOT_A_FOLLOWER {
            get {
                return ResourceManager.GetString("ERROR_CHALLENGE_NOT_A_FOLLOWER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Challenge not found.
        /// </summary>
        public static string ERROR_CHALLENGE_NOT_FOUND {
            get {
                return ResourceManager.GetString("ERROR_CHALLENGE_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This challenge does not belong to you.
        /// </summary>
        public static string ERROR_CHALLENGE_NOT_YOURS {
            get {
                return ResourceManager.GetString("ERROR_CHALLENGE_NOT_YOURS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot challenge yourself :P.
        /// </summary>
        public static string ERROR_CHALLENGE_YOURSELF {
            get {
                return ResourceManager.GetString("ERROR_CHALLENGE_YOURSELF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter &apos;type&apos; must be equal to &apos;video&apos; or &apos;picture&apos;.
        /// </summary>
        public static string ERROR_INVALID_PARAMETER_TYPE {
            get {
                return ResourceManager.GetString("ERROR_INVALID_PARAMETER_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You just have signed out.
        /// </summary>
        public static string ERROR_JUST_SIGNOUT {
            get {
                return ResourceManager.GetString("ERROR_JUST_SIGNOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing parameter: &apos;{0}&apos;.
        /// </summary>
        public static string ERROR_MISSING_PARAMETER {
            get {
                return ResourceManager.GetString("ERROR_MISSING_PARAMETER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops! Password incorrent.
        /// </summary>
        public static string ERROR_PASSWORD_INCORRECT {
            get {
                return ResourceManager.GetString("ERROR_PASSWORD_INCORRECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please sign in .
        /// </summary>
        public static string ERROR_PLEASE_SIGN_IN {
            get {
                return ResourceManager.GetString("ERROR_PLEASE_SIGN_IN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User already exists :/.
        /// </summary>
        public static string ERROR_USER_ALREADY_EXISTS {
            get {
                return ResourceManager.GetString("ERROR_USER_ALREADY_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User not found.
        /// </summary>
        public static string ERROR_USER_NOT_FOUND {
            get {
                return ResourceManager.GetString("ERROR_USER_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feed.
        /// </summary>
        public static string Feed {
            get {
                return ResourceManager.GetString("Feed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follower.
        /// </summary>
        public static string Follower {
            get {
                return ResourceManager.GetString("Follower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Followers.
        /// </summary>
        public static string Followers {
            get {
                return ResourceManager.GetString("Followers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Following.
        /// </summary>
        public static string Following {
            get {
                return ResourceManager.GetString("Following", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Following.
        /// </summary>
        public static string Followings {
            get {
                return ResourceManager.GetString("Followings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string General {
            get {
                return ResourceManager.GetString("General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I challenge you to.
        /// </summary>
        public static string IChallengeYouTo {
            get {
                return ResourceManager.GetString("IChallengeYouTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Just one second.
        /// </summary>
        public static string Just1Sec {
            get {
                return ResourceManager.GetString("Just1Sec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to just now.
        /// </summary>
        public static string JustNow {
            get {
                return ResourceManager.GetString("JustNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Like.
        /// </summary>
        public static string Like {
            get {
                return ResourceManager.GetString("Like", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Likes.
        /// </summary>
        public static string Likes {
            get {
                return ResourceManager.GetString("Likes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading.
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logging in.
        /// </summary>
        public static string LoggingIn {
            get {
                return ResourceManager.GetString("LoggingIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mute.
        /// </summary>
        public static string Mute {
            get {
                return ResourceManager.GetString("Mute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My profile.
        /// </summary>
        public static string MyProfile {
            get {
                return ResourceManager.GetString("MyProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}d.
        /// </summary>
        public static string NDaysAgo {
            get {
                return ResourceManager.GetString("NDaysAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network error.
        /// </summary>
        public static string NetworkError {
            get {
                return ResourceManager.GetString("NetworkError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Challenge.
        /// </summary>
        public static string NewChallenge {
            get {
                return ResourceManager.GetString("NewChallenge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dance like a super crazy.
        /// </summary>
        public static string NewChallengeDescriptionExample {
            get {
                return ResourceManager.GetString("NewChallengeDescriptionExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A drink.
        /// </summary>
        public static string NewChallengeRewardExample {
            get {
                return ResourceManager.GetString("NewChallengeRewardExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}h.
        /// </summary>
        public static string NHoursAgo {
            get {
                return ResourceManager.GetString("NHoursAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} min.
        /// </summary>
        public static string NMinutesAgo {
            get {
                return ResourceManager.GetString("NMinutesAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} months.
        /// </summary>
        public static string NMonthsAgo {
            get {
                return ResourceManager.GetString("NMonthsAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications.
        /// </summary>
        public static string Notifications {
            get {
                return ResourceManager.GetString("Notifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} weeks.
        /// </summary>
        public static string NWeeksAgo {
            get {
                return ResourceManager.GetString("NWeeksAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} years.
        /// </summary>
        public static string NYearsAgo {
            get {
                return ResourceManager.GetString("NYearsAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to last month.
        /// </summary>
        public static string OneMonthAgo {
            get {
                return ResourceManager.GetString("OneMonthAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to last week.
        /// </summary>
        public static string OneWeekAgo {
            get {
                return ResourceManager.GetString("OneWeekAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to last year.
        /// </summary>
        public static string OneYearAgo {
            get {
                return ResourceManager.GetString("OneYearAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to People.
        /// </summary>
        public static string People {
            get {
                return ResourceManager.GetString("People", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Picture.
        /// </summary>
        public static string Picture {
            get {
                return ResourceManager.GetString("Picture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait.
        /// </summary>
        public static string PleaseWait {
            get {
                return ResourceManager.GetString("PleaseWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refusing challenge.
        /// </summary>
        public static string RefusingChallenge {
            get {
                return ResourceManager.GetString("RefusingChallenge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reputation.
        /// </summary>
        public static string Reputation {
            get {
                return ResourceManager.GetString("Reputation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reward.
        /// </summary>
        public static string Reward {
            get {
                return ResourceManager.GetString("Reward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving.
        /// </summary>
        public static string Saving {
            get {
                return ResourceManager.GetString("Saving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select friend.
        /// </summary>
        public static string SelectFriend {
            get {
                return ResourceManager.GetString("SelectFriend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, something went wrong.
        /// </summary>
        public static string SomethingWentWrong {
            get {
                return ResourceManager.GetString("SomethingWentWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags.
        /// </summary>
        public static string Tags {
            get {
                return ResourceManager.GetString("Tags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unmute.
        /// </summary>
        public static string Unmute {
            get {
                return ResourceManager.GetString("Unmute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploading.
        /// </summary>
        public static string Uploading {
            get {
                return ResourceManager.GetString("Uploading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video.
        /// </summary>
        public static string Video {
            get {
                return ResourceManager.GetString("Video", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1d.
        /// </summary>
        public static string Yesterday {
            get {
                return ResourceManager.GetString("Yesterday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your e-mail.
        /// </summary>
        public static string YourEmail {
            get {
                return ResourceManager.GetString("YourEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your full name.
        /// </summary>
        public static string YourFullName {
            get {
                return ResourceManager.GetString("YourFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your username.
        /// </summary>
        public static string YourUsername {
            get {
                return ResourceManager.GetString("YourUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You were challenged!.
        /// </summary>
        public static string YouWereChallenged {
            get {
                return ResourceManager.GetString("YouWereChallenged", resourceCulture);
            }
        }
    }
}
